### ISSUE TITLE
Staging SRE-SE2 is not rejecting wrong submissions

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/SpeedRunEthereum#193]
I'm submitting a Challenge re-using the URL from another Challenge #number contract. 

In LIVE it's rejecting it, but in Staging it stays as `Submitted`.

Example: https://staging.speedrunethereum.com/builders/0x60f6692727B8a92b0AC5eC7db30DD83448F18aAf

**Comment by carletex** [comment]
This should be fixed now! Can you check @Pabl0cks ?

**Comment by Pabl0cks** [comment]
> This should be fixed now! Can you check @Pabl0cks ?

Yes! Now is rejecting without problem, tried re-submitting one of the pending challenges and got rejected also 🙌

Found a problem with "Updated" column in this version, on all my profiles it's always trying to load the date, but never finishes. Maybe it's a problem with the staging server, it's been a bit slow during the tests. Tried different networks but didn't fix it.

Here is a screenshot.

 ![image](https://github.com/BuidlGuidl/SpeedRunEthereum/assets/55535804/47d631c8-0d7f-41d5-b0f7-4f00e48ae80a)

**Comment by Pabl0cks** [comment]
> Yep, you are right, this was only an issue on the staging server. I needed to create some indexes on Firebase (staging) for this to work. It should be fixed now!

Great! Now is working like a charm 🙌

Tried all challenges with correct code, all being accepted. Also tried some rejected challenges (Chal 3 - 4 - 5) and we're getting the same reject reasons as with old SRE challenges.

Closing! 🔥🚀
